gameboy_action_freq: 24
gameboy_press_step: 8
gameboy_video_frame_stacks: 3
gameboy_headed_emulation_speed: None # Set this to a multiplier to speed up emulation with a window, e.g. 2 for 2x speed
gameboy_max_steps: 10000
gameboy_hard_max_steps: 1000000
gameboy_default_save_video: false
gameboy_headless_render: true # Can set to false for non-visual agents.
gameboy_reduce_video_resolution: true
gameboy_dev_play_stop: true # If true, will immediately freeze the emulator and allow the user to perform useful state specific actions. Only for development.