pokemon_red_rom_data_path: "rom_data/pokemon/pokemon_red/"
pokemon_crystal_rom_data_path: "rom_data/pokemon/pokemon_crystal/"
pokemon_fools_gold_rom_data_path: "rom_data/pokemon/pokemon_fools_gold/"
pokemon_prism_rom_data_path: "rom_data/pokemon/pokemon_prism/"
pokemon_brown_rom_data_path: "rom_data/pokemon/pokemon_brown/"
pokemon_starbeasts_rom_data_path: "rom_data/pokemon/pokemon_starbeasts/"