debug_mode: false
debug_skip_lm: false # Will skip all LM calls, to allow debugging on systems without LM access. 
ocr_batch_size: 16
ocr_max_new_tokens: 20
executor_vlm_model: Qwen/Qwen3-VL-8B-Instruct # The VLM that handles simple goal directed usage of High Level Actions. Use the same model as the backbone to avoid loading multiple models.
executor_vlm_kind: qwen3vl
executor_action_buffer_size: 5
executor_retries_per_action: 3
executor_max_steps: 15